# Generated by Django 4.2.21 on 2025-05-15 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='evaluaciones/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
