# Generated by Django 4.2.21 on 2025-05-15 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_evaluacion_archivo_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='evaluaciones_pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Archivo PDF'),
        ),
    ]
